'''                  EJERCICIO NUMERO #72
CREAR UNA CLASE RECTANGULO CON LOS SIGUIENTES ATRIBUTOSñ
BASE : BASE DEL RECTANGULO
ALTURA : ALTURA DEL RECTANGULO
LA CLASE DEBE TENER LOS SIGUIENTES METODOS:
<> __INIT__(SELF, BASE, ALTURA: INICIALIZA LOS ATRIBUTOS
DE LA CLASE.
<>CALCULAR_AREA(SELF: CALCULA Y DEVUELVE EL AREA DEL RECTANGULO
<>CALCULAR_PERIMETRO(SELF): CALCULA Y DEVUELVE EL PERIMETRO DEL RECTANGULO.))'''