'''                  EJERCICIO NUMERO #72
CREAR UNA CLASE CIRCULO CON LOS SIGUIENTES ATRIBUTOS:
<> RADIO: RADIO DEL CIRCULO
LA CLASE DEBE TENER LOS SIGUIENTES METODOSl 
<>__INIT__(SELF, RADIO) : INICIALIZA LOS ATRIBUTOS DE LA CLASE
<>CALCULAR_AREA(SELF) : CALCULA Y DEVUELVE EL AREA DEL CIRCULO
<>CALCULAR_PERIMETRO(SELF) : CALCULA Y DEVUELVE EL PERIMETRO DEL CIRCULO'''