'''                  EJERCICIO NUMERO #75
CREAR UNA CLASE COCHE CON LOS ATRIBUTOS:
MARCA, MODELO, MATRICULA, KM
CON LOS METODOS:
INIT COMO CONSTRUCTOR 
AVANCZAR(KM) ESTE AUENTA EL VALOR DE KM EN LA CANTIDAD'''