'''                  EJERCICIO NUMERO #76
CREAR UNA CLASE ANIMAL CON LOS ATRIBUTOS
ESPECIE Y NOMBRE
LA CLASE DEBE TENER LOS METODOS:
INIT Y HABLAR()
EL METODO HABLAR NOS RETORNA UNA PALABRA SEGUN LA INTERPRETACION 
DEL SONIDO COMO UN PERRRO SERIA "GUAU"'''