'''                  EJERCICIO NUMERO #77
CREAR UNA CLASE LLAMADA PERSONA.
*CON LOS ATRIBUTOS: NOMBRE Y EDAD:
*LOS SETTERS Y GETTERS
PARA CADA UNO DE LOS ATRIBUTOS.
*MOSTRAR(): MUESTRA LOS DATOS DE LA PERSONA.
*ESMAYOREDEEDAD(): DEVUELVE UN VALOR LOGICO INDICANDO
SI ES MAYOR DE EDAD'''