'''                  EJERCICIO NUMERO #78
CREAR UNA CLASE PERSONA Y OTRA CLASE ESTUDIANTE.
LA CLASE PERSONA TIENE EL ATRIBUTO NOMBRE Y EL METODO MOSTRAR_NOMBRE()
LA CLASE ESTUDIANTE DEBE HEREDAR DE LA CLASE PERSONA Y UTILIZAR EL METODO MOSTRAR_NOMBNRE()
DE LA CLASE PERSONA'''